import { ChWitcher, ChWitcherDef } from "./ch_witcher.model";

const geraltDef: ChWitcherDef = {
    img: '/img/geralt.png',
    gender: "M",
    age: 120,
    race: "Witcher",
    background: "The strongest witcher of all remaining ones. From the school of the wolf.",
    appearance: "Always dressed with the wolf school armor. Rocks long white hair.",
    personality: "Quiet and reserved, also a bit cold sometimes due to the mutations.",
    life: "A life of hardship, combat and monsters.",
    encumberance: 0,
    crowns: 0,
    reputation: 10,
    ip: 0,
    baseStatSet: {
        INT: 6,
        REF: 14,
        DEX: 10,
        BODY: 8,
        SPD: 9,
        EMP: 3,
        CRA: 5,
        WILL: 8,
        LUCK: 3
    },
    derivStatSet: {
        VIGOR: 7,
        STUN: 8,
        RUN: 27,
        LEAP: 5,
        HP: 55,
        STA: 40,
        ENC: 80,
        REC: 8,
        PUNCH: 2,
        KICK: 6
    },
    profession: "Witcher",
    baseSkillSet: {
        Awareness: 9,
        Business: 0,
        Deduction: 8,
        Education: 0,
        Language: 0,
        MonsterLore: 0,
        SocialEtiquette: 0,
        Streetwise: 0,
        Tactics: 0,
        Teaching: 0,
        WildernessSurival: 9,
        Brawling: 6,
        DodgeEscape: 10,
        Melee: 7,
        SmallBlades: 9,
        StaffSpear: 0,
        Swordsmanship: 11,
        Riding: 4,
        Sailing: 0,
        Athletics: 10,
        Archery: 0,
        Crossbow: 6,
        SleightOfHand: 0,
        Stealth: 8,
        Physique: 6,
        Endurance: 10,
        Charisma: 0,
        Deceit: 0,
        Persuasion: 0,
        Leadership: 0,
        Seduction: 0,
        FineArts: 0,
        Performance: 0,
        Gambling: 0,
        GroomingStyle: 0,
        HumanPerception: 0,
        Alchemy: 5,
        Forgery: 0,
        Crafting: 0,
        Disguise: 0,
        TrapCrafting: 0,
        FirstAid: 0,
        PickLock: 0,
        Courage: 0,
        HexWeaving: 0,
        SpellCasting: 8,
        RitualCrafting: 0,
        ResistMagic: 0,
        ResistCoertion: 0,
        Intimidation: 9
    },
    profSkillSet: {
        WitcherTraining: 10,
        Meditation: 10,
        MagicalSource: 10,
        Heliotrope: 6,
        IronStomach: 8,
        Frenzy: 8,
        Transmutation: 6,
        ParryArrows: 10, 
        QuickStrike: 8,
        Whirl: 8
    },
    id: "",
    name: "Geralt of Rivia"
}
export const geralt: ChWitcher = new ChWitcher(geraltDef);